name: med_call_user
description: A Flutter project for home-based medical services
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management & Architecture
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4            # Стабильная версия, совместимая с injectable_generator
  injectable: ^2.3.2       # Совместимая версия для генератора

  # Network
  dio: ^5.4.0

  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # UI Utils
  equatable: ^2.0.5
  gap: ^3.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.6        # Перенёс сюда, т.к. нужен только на этапе генерации
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1   # Стабильная версия, совместимая с analyzer 6.x
  freezed: ^2.4.5

dependency_overrides:
  analyzer: ^6.2.0            # Принудительно понижаем analyzer, чтобы json_serializable заработал